# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-17 21:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=30, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.')], verbose_name='Phone Number')),
                ('street_address1', models.CharField(max_length=40, verbose_name='Street Address 1')),
                ('street_address2', models.CharField(max_length=40, verbose_name='Street Address 2')),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('town_city', models.CharField(max_length=40, verbose_name='Town/City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('employee', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='profile')),
            ],
        ),
    ]
