# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='street_address1',
            field=models.CharField(max_length=40, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street_address2',
            field=models.CharField(max_length=40, verbose_name='Street Address 2'),
        ),
    ]
