# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee',
            field=models.BooleanField(default=False),
        ),
    ]
