# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-15 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190915_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(max_length=50),
        ),
    ]
