# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address1',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address2',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
