# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191102_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='town_city',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
