# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-17 21:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.')], verbose_name='Phone Number')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('town_city', models.CharField(max_length=40, verbose_name='Town/City')),
                ('street_address1', models.CharField(max_length=40, verbose_name='Street Address 1')),
                ('street_address2', models.CharField(max_length=40, verbose_name='Street Address 2')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderList')),
            ],
        ),
    ]
