# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-15 14:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='full_name',
            field=models.CharField(max_length=30, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='postcode',
            field=models.CharField(max_length=50, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='street_address1',
            field=models.CharField(max_length=40, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='street_address2',
            field=models.CharField(max_length=40, verbose_name='Street Address 2'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='town_city',
            field=models.CharField(max_length=40, verbose_name='Town/City'),
        ),
    ]
