# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20191125_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='profiles.UserProfile'),
        ),
    ]
