# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('title', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=500)),
                ('review_left', models.BooleanField(default=False)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_table', to='orders.OrderList')),
            ],
        ),
    ]
