# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='review_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Reviews'),
            preserve_default=False,
        ),
    ]
