# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user_int',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='review_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='gallery.Reviews'),
        ),
    ]
