# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20191126_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
