# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-18 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191118_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='username',
        ),
    ]
