# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('gallery', '0005_auto_20191113_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='order_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderList'),
            preserve_default=False,
        ),
    ]
