# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_reviews_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_left',
            field=models.BooleanField(default=False),
        ),
    ]
