# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('products', '0022_remove_damage_is_damaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('order_status', models.CharField(max_length=25)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Services')),
            ],
        ),
    ]
