# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20191014_2102'),
        ('auth', '0008_alter_user_username_max_length'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('order_status', models.CharField(max_length=50, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Services')),
            ],
        ),
        migrations.RemoveField(
            model_name='order_list',
            name='serviceID',
        ),
        migrations.RemoveField(
            model_name='order_list',
            name='user',
        ),
        migrations.DeleteModel(
            name='order_list',
        ),
    ]
