# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191014_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
