# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191014_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_status',
            field=models.CharField(default='Waiting', max_length=25),
            preserve_default=False,
        ),
    ]
