# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191014_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
