# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191014_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='username',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
