# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderlist_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='paid',
        ),
    ]
