# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191102_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
