# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_needed', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, default=products.models.increment_quote_number, max_length=500, null=True)),
                ('damage_details', models.TextField(blank=True, max_length=500)),
                ('car_make', models.CharField(choices=[('', 'Please choose a Make'), ('audi', 'Audi'), ('bmw', 'BMW'), ('toyota', 'Toyota'), ('nissan', 'Nissan'), ('mini', 'Mini')], default='Please choose a Make', max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('user', models.CharField(max_length=50)),
                ('damage', models.ManyToManyField(to='products.Damage')),
                ('optional_service', models.ManyToManyField(to='products.OptionalService')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='quotes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='WrapColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='wrap_colour')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='type_of_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TypeOfService'),
        ),
        migrations.AddField(
            model_name='services',
            name='wrap_colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.WrapColour'),
        ),
    ]
