# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='damage',
        ),
        migrations.AddField(
            model_name='services',
            name='damage',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='products.Damage'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='services',
            name='optional_service',
        ),
        migrations.AddField(
            model_name='services',
            name='optional_service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.OptionalService'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
