# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190925_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='damage',
        ),
        migrations.AddField(
            model_name='services',
            name='damage',
            field=models.ManyToManyField(to='products.Damage'),
        ),
        migrations.RemoveField(
            model_name='services',
            name='optional_service',
        ),
        migrations.AddField(
            model_name='services',
            name='optional_service',
            field=models.ManyToManyField(to='products.OptionalService'),
        ),
        migrations.RemoveField(
            model_name='services',
            name='type_of_service',
        ),
        migrations.AddField(
            model_name='services',
            name='type_of_service',
            field=models.ManyToManyField(to='products.TypeOfService'),
        ),
    ]
