# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190925_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofservice',
            name='image',
            field=models.ImageField(blank=True, upload_to='quotes'),
        ),
    ]
