# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191004_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='damage',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='services',
            name='optional_service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='type_of_service',
            field=models.CharField(max_length=50),
        ),
    ]
