# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191004_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrapColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='wrap_colour')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='damage',
            field=models.CharField(max_length=240),
        ),
    ]
