# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191004_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='type_of_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.TypeOfService'),
        ),
    ]
