# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191007_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='damage_details',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='services',
            name='wrap_colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.WrapColour'),
        ),
    ]
