# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191007_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id',
        ),
        migrations.AlterField(
            model_name='services',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
