# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20191007_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='damage',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='optional_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.OptionalService'),
        ),
        migrations.AlterField(
            model_name='services',
            name='type_of_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TypeOfService'),
        ),
        migrations.AlterField(
            model_name='services',
            name='wrap_colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.WrapColour'),
        ),
    ]
