# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20191007_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='damage',
        ),
        migrations.AddField(
            model_name='services',
            name='damage',
            field=models.ManyToManyField(null=True, to='products.Damage'),
        ),
    ]
