# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20191007_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='damage',
        ),
        migrations.AddField(
            model_name='services',
            name='damage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Damage'),
        ),
    ]
