# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_damage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='is_damaged',
        ),
    ]
