# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_damage_is_damaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='invoice_no',
            field=models.CharField(blank=True, default=products.models.increment_quote_number, max_length=500, null=True),
        ),
    ]
