# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20191031_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='car_model',
            field=models.CharField(default='Please choose a model', max_length=30),
        ),
    ]
