# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20191031_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='car_make',
            field=models.CharField(choices=[('NA', 'Please choose a Make'), ('audi', 'Audi'), ('bmw', 'BMW'), ('toyota', 'Toyota'), ('nissan', 'Nissan'), ('mini', 'Mini')], default='Please choose a Make', max_length=6),
        ),
        migrations.AlterField(
            model_name='services',
            name='car_model',
            field=models.CharField(choices=[('NA', 'Please choose a Model')], default='Please choose a model', max_length=30),
        ),
    ]
